name: KasHubServer
version: ${version}
main: kasperstudios.kashub.server.KasHubServerPlugin
api-version: 1.21
authors: [KasperStudios]
description: Server-side controller for KasHub mod.

commands:
  kashub:
    description: Main command for KasHub configuration
    usage: /kashub <reload|info>
    permission: kashub.admin
    aliases: [khserver]

permissions:
  kashub.admin:
    description: Allows managing KasHub server settings
    default: op
